### ISSUE TITLE
when will the full "modified cellular stack", thanks

### ISSUE THREAD

**Issue by chernwuqq** [SyNSec-den/DIKEUE#1]
the homepage said: "Upon request from the vendors, we are not releasing the modified cellular stack used in the FSM Inference module of our framework at this moment. "
As it has passed about half a year, could you release the full "modified cellular stack"?

**Comment by Imtiazkarimik23** [comment]
Many thanks for your interest. We have been waiting for different vendors to complete the vulnerability patching process for all the different device models. The overall waiting period was unusually long and it is not possible to patch all the devices in the market. With this current situation, we have decided to open-source everything related to the project. We hope researchers will use the tool responsibly.
